[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn backend.config.wsgi"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 100

[env]
PYTHONUNBUFFERED = "1"
PORT = "8000"
